package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AbteilungTask generated by hbm2java
 */
@Entity
@Table(name = "AbteilungTask", catalog = "Skillmanager", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Abteilung", "Task" }))
public class AbteilungTask implements java.io.Serializable {

	private Integer abteilungTaskId;
	private Task task;
	private Abteilung abteilung;

	public AbteilungTask() {
	}

	public AbteilungTask(Task task, Abteilung abteilung) {
		this.task = task;
		this.abteilung = abteilung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AbteilungTaskId", unique = true, nullable = false)
	public Integer getAbteilungTaskId() {
		return this.abteilungTaskId;
	}

	public void setAbteilungTaskId(Integer abteilungTaskId) {
		this.abteilungTaskId = abteilungTaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Task", nullable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Abteilung", nullable = false)
	public Abteilung getAbteilung() {
		return this.abteilung;
	}

	public void setAbteilung(Abteilung abteilung) {
		this.abteilung = abteilung;
	}

}
