package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AbteilungProjekt generated by hbm2java
 */
@Entity
@Table(name = "AbteilungProjekt", catalog = "Skillmanager", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Abteilung", "Projekt" }))
public class AbteilungProjekt implements java.io.Serializable {

	private Integer abteilungProjektId;
	private Projekt projekt;
	private Abteilung abteilung;

	public AbteilungProjekt() {
	}

	public AbteilungProjekt(Projekt projekt, Abteilung abteilung) {
		this.projekt = projekt;
		this.abteilung = abteilung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AbteilungProjektId", unique = true, nullable = false)
	public Integer getAbteilungProjektId() {
		return this.abteilungProjektId;
	}

	public void setAbteilungProjektId(Integer abteilungProjektId) {
		this.abteilungProjektId = abteilungProjektId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Projekt", nullable = false)
	public Projekt getProjekt() {
		return this.projekt;
	}

	public void setProjekt(Projekt projekt) {
		this.projekt = projekt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Abteilung", nullable = false)
	public Abteilung getAbteilung() {
		return this.abteilung;
	}

	public void setAbteilung(Abteilung abteilung) {
		this.abteilung = abteilung;
	}

}
