package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BenutzerRole generated by hbm2java
 */
@Entity
@Table(name = "BenutzerRole", catalog = "Skillmanager", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Benutzer", "Role" }))
public class BenutzerRole implements java.io.Serializable {

	private Integer benutzerRoleId;
	private Benutzer benutzer;
	private Role role;

	public BenutzerRole() {
	}

	public BenutzerRole(Benutzer benutzer, Role role) {
		this.benutzer = benutzer;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BenutzerRoleId", unique = true, nullable = false)
	public Integer getBenutzerRoleId() {
		return this.benutzerRoleId;
	}

	public void setBenutzerRoleId(Integer benutzerRoleId) {
		this.benutzerRoleId = benutzerRoleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Benutzer", nullable = false)
	public Benutzer getBenutzer() {
		return this.benutzer;
	}

	public void setBenutzer(Benutzer benutzer) {
		this.benutzer = benutzer;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((benutzer == null) ? 0 : benutzer.hashCode());
		result = prime * result
				+ ((benutzerRoleId == null) ? 0 : benutzerRoleId.hashCode());
		result = prime * result + ((role == null) ? 0 : role.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BenutzerRole other = (BenutzerRole) obj;
		if (benutzer == null) {
			if (other.benutzer != null)
				return false;
		} else if (!benutzer.equals(other.benutzer))
			return false;
		if (benutzerRoleId == null) {
			if (other.benutzerRoleId != null)
				return false;
		} else if (!benutzerRoleId.equals(other.benutzerRoleId))
			return false;
		if (role == null) {
			if (other.role != null)
				return false;
		} else if (!role.equals(other.role))
			return false;
		return true;
	}
	
	
	
	
	
	

}
