package ch.business.quickline.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LernObjekt generated by hbm2java
 */
@Entity
@Table(name = "LernObjekt", catalog = "Skillmanager")
public class LernObjekt implements java.io.Serializable {

	private Integer lernObjektId;
	private Skill skill;
	private String lernObjektArt;
	private String lernObjektName;
	private Set<Task> tasks = new HashSet<Task>(0);

	public LernObjekt() {
	}

	public LernObjekt(Skill skill, String lernObjektArt, String lernObjektName) {
		this.skill = skill;
		this.lernObjektArt = lernObjektArt;
		this.lernObjektName = lernObjektName;
	}

	public LernObjekt(Skill skill, String lernObjektArt, String lernObjektName,
			Set<Task> tasks) {
		this.skill = skill;
		this.lernObjektArt = lernObjektArt;
		this.lernObjektName = lernObjektName;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LernObjektID", unique = true, nullable = false)
	public Integer getLernObjektId() {
		return this.lernObjektId;
	}

	public void setLernObjektId(Integer lernObjektId) {
		this.lernObjektId = lernObjektId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LernObjektSkill", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@Column(name = "LernObjektArt", nullable = false, length = 30)
	public String getLernObjektArt() {
		return this.lernObjektArt;
	}

	public void setLernObjektArt(String lernObjektArt) {
		this.lernObjektArt = lernObjektArt;
	}

	@Column(name = "LernObjektName", nullable = false, length = 30)
	public String getLernObjektName() {
		return this.lernObjektName;
	}

	public void setLernObjektName(String lernObjektName) {
		this.lernObjektName = lernObjektName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "LernObjektTask", catalog = "Skillmanager", joinColumns = { @JoinColumn(name = "LernObjekt", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Task", nullable = false, updatable = false) })
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
