package ch.business.quickline.domain;
// default package
// Generated 10.04.2015 18:41:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MitarbeiterSkill generated by hbm2java
 */
@Entity
@Table(name = "MitarbeiterSkill", catalog = "Skillmanager")
public class MitarbeiterSkill implements java.io.Serializable {

	private Integer mitarbeiterSkillId;
	private Mitarbeiter mitarbeiter;
	private Skill skill;
	private Integer masterBewertung;
	private Integer selbstBewertung;

	public MitarbeiterSkill() {
	}

	public MitarbeiterSkill(Mitarbeiter mitarbeiter, Skill skill) {
		this.mitarbeiter = mitarbeiter;
		this.skill = skill;
	}

	public MitarbeiterSkill(Mitarbeiter mitarbeiter, Skill skill,
			Integer masterBewertung, Integer selbstBewertung) {
		this.mitarbeiter = mitarbeiter;
		this.skill = skill;
		this.masterBewertung = masterBewertung;
		this.selbstBewertung = selbstBewertung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MitarbeiterSkillID", unique = true, nullable = false)
	public Integer getMitarbeiterSkillId() {
		return this.mitarbeiterSkillId;
	}

	public void setMitarbeiterSkillId(Integer mitarbeiterSkillId) {
		this.mitarbeiterSkillId = mitarbeiterSkillId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mitarbeiter", nullable = false)
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Skill", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@Column(name = "MasterBewertung")
	public Integer getMasterBewertung() {
		return this.masterBewertung;
	}

	public void setMasterBewertung(Integer masterBewertung) {
		this.masterBewertung = masterBewertung;
	}

	@Column(name = "SelbstBewertung")
	public Integer getSelbstBewertung() {
		return this.selbstBewertung;
	}

	public void setSelbstBewertung(Integer selbstBewertung) {
		this.selbstBewertung = selbstBewertung;
	}

}
