package ch.business.quickline.domain;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * MitarbeiterSkill generated by hbm2java
 */
@Entity
@Table(name = "MitarbeiterSkill", catalog = "Skillmanager")
public class MitarbeiterSkill implements java.io.Serializable {

	private MitarbeiterSkillId id;
	private Mitarbeiter mitarbeiter;
	private Skill skill;
	private Integer masterBewertung;
	private Integer selbstBewertung;

	public MitarbeiterSkill() {
	}

	public MitarbeiterSkill(MitarbeiterSkillId id, Mitarbeiter mitarbeiter,
			Skill skill) {
		this.id = id;
		this.mitarbeiter = mitarbeiter;
		this.skill = skill;
	}

	public MitarbeiterSkill(MitarbeiterSkillId id, Mitarbeiter mitarbeiter,
			Skill skill, Integer masterBewertung, Integer selbstBewertung) {
		this.id = id;
		this.mitarbeiter = mitarbeiter;
		this.skill = skill;
		this.masterBewertung = masterBewertung;
		this.selbstBewertung = selbstBewertung;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mitarbeiter", column = @Column(name = "Mitarbeiter", nullable = false)),
			@AttributeOverride(name = "skill", column = @Column(name = "Skill", nullable = false)) })
	public MitarbeiterSkillId getId() {
		return this.id;
	}

	public void setId(MitarbeiterSkillId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Mitarbeiter", nullable = false, insertable = false, updatable = false)
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Skill", nullable = false, insertable = false, updatable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@Column(name = "MasterBewertung")
	public Integer getMasterBewertung() {
		return this.masterBewertung;
	}

	public void setMasterBewertung(Integer masterBewertung) {
		this.masterBewertung = masterBewertung;
	}

	@Column(name = "SelbstBewertung")
	public Integer getSelbstBewertung() {
		return this.selbstBewertung;
	}

	public void setSelbstBewertung(Integer selbstBewertung) {
		this.selbstBewertung = selbstBewertung;
	}

}
