package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MitarbeiterTask generated by hbm2java
 */
@Entity
@Table(name = "MitarbeiterTask", catalog = "Skillmanager", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Mitarbeiter", "Task" }))
public class MitarbeiterTask implements java.io.Serializable {

	private Integer mitarbeiterTaskId;
	private Mitarbeiter mitarbeiter;
	private Task task;

	public MitarbeiterTask() {
	}

	public MitarbeiterTask(Mitarbeiter mitarbeiter, Task task) {
		this.mitarbeiter = mitarbeiter;
		this.task = task;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MitarbeiterTaskId", unique = true, nullable = false)
	public Integer getMitarbeiterTaskId() {
		return this.mitarbeiterTaskId;
	}

	public void setMitarbeiterTaskId(Integer mitarbeiterTaskId) {
		this.mitarbeiterTaskId = mitarbeiterTaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mitarbeiter", nullable = false)
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Task", nullable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

}
