package ch.business.quickline.domain;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MitarbeiterSkillId generated by hbm2java
 */
@Embeddable
public class MitarbeiterSkillId implements java.io.Serializable {

	private int mitarbeiter;
	private int skill;

	public MitarbeiterSkillId() {
	}

	public MitarbeiterSkillId(int mitarbeiter, int skill) {
		this.mitarbeiter = mitarbeiter;
		this.skill = skill;
	}

	@Column(name = "Mitarbeiter", nullable = false)
	public int getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(int mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@Column(name = "Skill", nullable = false)
	public int getSkill() {
		return this.skill;
	}

	public void setSkill(int skill) {
		this.skill = skill;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MitarbeiterSkillId))
			return false;
		MitarbeiterSkillId castOther = (MitarbeiterSkillId) other;

		return (this.getMitarbeiter() == castOther.getMitarbeiter())
				&& (this.getSkill() == castOther.getSkill());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMitarbeiter();
		result = 37 * result + this.getSkill();
		return result;
	}

}
