package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projekt generated by hbm2java
 */
@Entity
@Table(name = "Projekt", catalog = "Skillmanager")
public class Projekt implements java.io.Serializable {

	private Integer projektId;
	private String projektName;
	private String projektBeschreibung;
	private Date projektBeginn;
	private Date projektEnde;
	private Set<ProjektTask> projektTasks = new HashSet<ProjektTask>(0);
	private Set<AbteilungProjekt> abteilungProjekts = new HashSet<AbteilungProjekt>(
			0);

	public Projekt() {
	}

	public Projekt(String projektName, String projektBeschreibung) {
		this.projektName = projektName;
		this.projektBeschreibung = projektBeschreibung;
	}

	public Projekt(String projektName, String projektBeschreibung,
			Date projektBeginn, Date projektEnde,
			Set<ProjektTask> projektTasks,
			Set<AbteilungProjekt> abteilungProjekts) {
		this.projektName = projektName;
		this.projektBeschreibung = projektBeschreibung;
		this.projektBeginn = projektBeginn;
		this.projektEnde = projektEnde;
		this.projektTasks = projektTasks;
		this.abteilungProjekts = abteilungProjekts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ProjektID", unique = true, nullable = false)
	public Integer getProjektId() {
		return this.projektId;
	}

	public void setProjektId(Integer projektId) {
		this.projektId = projektId;
	}

	@Column(name = "ProjektName", nullable = false, length = 30)
	public String getProjektName() {
		return this.projektName;
	}

	public void setProjektName(String projektName) {
		this.projektName = projektName;
	}

	@Column(name = "ProjektBeschreibung", nullable = false, length = 500)
	public String getProjektBeschreibung() {
		return this.projektBeschreibung;
	}

	public void setProjektBeschreibung(String projektBeschreibung) {
		this.projektBeschreibung = projektBeschreibung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ProjektBeginn", length = 10)
	public Date getProjektBeginn() {
		return this.projektBeginn;
	}

	public void setProjektBeginn(Date projektBeginn) {
		this.projektBeginn = projektBeginn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ProjektEnde", length = 10)
	public Date getProjektEnde() {
		return this.projektEnde;
	}

	public void setProjektEnde(Date projektEnde) {
		this.projektEnde = projektEnde;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projekt")
	public Set<ProjektTask> getProjektTasks() {
		return this.projektTasks;
	}

	public void setProjektTasks(Set<ProjektTask> projektTasks) {
		this.projektTasks = projektTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projekt")
	public Set<AbteilungProjekt> getAbteilungProjekts() {
		return this.abteilungProjekts;
	}

	public void setAbteilungProjekts(Set<AbteilungProjekt> abteilungProjekts) {
		this.abteilungProjekts = abteilungProjekts;
	}

}
