package ch.business.quickline.domain;
// default package
// Generated 15.04.2015 23:50:36 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Qualifikation generated by hbm2java
 */
@Entity
@Table(name = "Qualifikation", catalog = "Skillmanager")
public class Qualifikation implements java.io.Serializable {

	private Integer qualifikationId;
	private String qualifikationName;
	private String qualifikationTyp;
	private Set<Mitarbeiter> mitarbeiters = new HashSet<Mitarbeiter>(0);

	public Qualifikation() {
	}

	public Qualifikation(String qualifikationName, String qualifikationTyp) {
		this.qualifikationName = qualifikationName;
		this.qualifikationTyp = qualifikationTyp;
	}

	public Qualifikation(String qualifikationName, String qualifikationTyp,
			Set<Mitarbeiter> mitarbeiters) {
		this.qualifikationName = qualifikationName;
		this.qualifikationTyp = qualifikationTyp;
		this.mitarbeiters = mitarbeiters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QualifikationID", unique = true, nullable = false)
	public Integer getQualifikationId() {
		return this.qualifikationId;
	}

	public void setQualifikationId(Integer qualifikationId) {
		this.qualifikationId = qualifikationId;
	}

	@Column(name = "QualifikationName", nullable = false, length = 30)
	public String getQualifikationName() {
		return this.qualifikationName;
	}

	public void setQualifikationName(String qualifikationName) {
		this.qualifikationName = qualifikationName;
	}

	@Column(name = "QualifikationTyp", nullable = false, length = 30)
	public String getQualifikationTyp() {
		return this.qualifikationTyp;
	}

	public void setQualifikationTyp(String qualifikationTyp) {
		this.qualifikationTyp = qualifikationTyp;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "MitarbeiterQualifikation", catalog = "Skillmanager", joinColumns = { @JoinColumn(name = "Qualifikation", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Mitarbeiter", nullable = false, updatable = false) })
	public Set<Mitarbeiter> getMitarbeiters() {
		return this.mitarbeiters;
	}

	public void setMitarbeiters(Set<Mitarbeiter> mitarbeiters) {
		this.mitarbeiters = mitarbeiters;
	}

}
