package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SkillTask generated by hbm2java
 */
@Entity
@Table(name = "SkillTask", catalog = "Skillmanager", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Skill", "Task" }))
public class SkillTask implements java.io.Serializable {

	private Integer skillTaskId;
	private Task task;
	private Skill skill;

	public SkillTask() {
	}

	public SkillTask(Task task, Skill skill) {
		this.task = task;
		this.skill = skill;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SkillTaskId", unique = true, nullable = false)
	public Integer getSkillTaskId() {
		return this.skillTaskId;
	}

	public void setSkillTaskId(Integer skillTaskId) {
		this.skillTaskId = skillTaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Task", nullable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Skill", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

}
