package ch.business.quickline.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SkillMaster generated by hbm2java
 */
@Entity
@Table(name = "SkillMaster", catalog = "Skillmanager")
public class SkillMaster implements java.io.Serializable {

	private int master;
	private Mitarbeiter mitarbeiter;
	private Set<Skill> skills = new HashSet<Skill>(0);

	public SkillMaster() {
	}

	public SkillMaster(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	public SkillMaster(Mitarbeiter mitarbeiter, Set<Skill> skills) {
		this.mitarbeiter = mitarbeiter;
		this.skills = skills;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "mitarbeiter"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Master", unique = true, nullable = false)
	public int getMaster() {
		return this.master;
	}

	public void setMaster(int master) {
		this.master = master;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skillMaster")
	public Set<Skill> getSkills() {
		return this.skills;
	}

	public void setSkills(Set<Skill> skills) {
		this.skills = skills;
	}

}
