package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ch.business.quickline.domain.MitarbeiterSkill;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "Skill", catalog = "Skillmanager")
public class Skill implements java.io.Serializable {

	private Integer skillId;
	private Gruppe gruppe;
	private String skillName;
	private String skillBeschreibung;
	private BigDecimal skillMasterBewertungDurchschnitt;
	private BigDecimal skillSelbstBewertungDurchschnitt;
	private Set<SkillTask> skillTasks = new HashSet<SkillTask>(0);
	private Set<SkillMaster> skillMasters = new HashSet<SkillMaster>(0);
	private Set<MitarbeiterSkill> mitarbeiterSkills = new HashSet<MitarbeiterSkill>(
			0);

	public Skill() {
	}

	public Skill(Gruppe gruppe, String skillName) {
		this.gruppe = gruppe;
		this.skillName = skillName;
	}

	public Skill(Gruppe gruppe, String skillName, String skillBeschreibung,
			BigDecimal skillMasterBewertungDurchschnitt,
			BigDecimal skillSelbstBewertungDurchschnitt,
			Set<SkillTask> skillTasks, Set<SkillMaster> skillMasters,
			Set<MitarbeiterSkill> mitarbeiterSkills) {
		this.gruppe = gruppe;
		this.skillName = skillName;
		this.skillBeschreibung = skillBeschreibung;
		this.skillMasterBewertungDurchschnitt = skillMasterBewertungDurchschnitt;
		this.skillSelbstBewertungDurchschnitt = skillSelbstBewertungDurchschnitt;
		this.skillTasks = skillTasks;
		this.skillMasters = skillMasters;
		this.mitarbeiterSkills = mitarbeiterSkills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SkillID", unique = true, nullable = false)
	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Gruppe", nullable = false)
	public Gruppe getGruppe() {
		return this.gruppe;
	}

	public void setGruppe(Gruppe gruppe) {
		this.gruppe = gruppe;
	}

	@Column(name = "SkillName", nullable = false, length = 30)
	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	@Column(name = "SkillBeschreibung", length = 500)
	public String getSkillBeschreibung() {
		return this.skillBeschreibung;
	}

	public void setSkillBeschreibung(String skillBeschreibung) {
		this.skillBeschreibung = skillBeschreibung;
	}

	@Column(name = "SkillMasterBewertungDurchschnitt", precision = 10)
	public BigDecimal getSkillMasterBewertungDurchschnitt() {
		return this.skillMasterBewertungDurchschnitt;
	}

	public void setSkillMasterBewertungDurchschnitt(
			BigDecimal skillMasterBewertungDurchschnitt) {
		this.skillMasterBewertungDurchschnitt = skillMasterBewertungDurchschnitt;
	}

	@Column(name = "SkillSelbstBewertungDurchschnitt", precision = 10)
	public BigDecimal getSkillSelbstBewertungDurchschnitt() {
		return this.skillSelbstBewertungDurchschnitt;
	}

	public void setSkillSelbstBewertungDurchschnitt(
			BigDecimal skillSelbstBewertungDurchschnitt) {
		this.skillSelbstBewertungDurchschnitt = skillSelbstBewertungDurchschnitt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
	public Set<SkillTask> getSkillTasks() {
		return this.skillTasks;
	}

	public void setSkillTasks(Set<SkillTask> skillTasks) {
		this.skillTasks = skillTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
	public Set<SkillMaster> getSkillMasters() {
		return this.skillMasters;
	}

	public void setSkillMasters(Set<SkillMaster> skillMasters) {
		this.skillMasters = skillMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
	public Set<MitarbeiterSkill> getMitarbeiterSkills() {
		return this.mitarbeiterSkills;
	}

	public void setMitarbeiterSkills(Set<MitarbeiterSkill> mitarbeiterSkills) {
		this.mitarbeiterSkills = mitarbeiterSkills;
	}
	
	public String toString(){
		return String.format("%s" , getSkillName() );
	}
	
	

}
