package ch.business.quickline.domain;
// default package
// Generated 21.05.2015 20:36:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "Task", catalog = "Skillmanager")
public class Task implements java.io.Serializable {

	private Integer taskId;
	private String taskName;
	private String taskBeschreibung;
	private Set<AbteilungTask> abteilungTasks = new HashSet<AbteilungTask>(0);
	private Set<SkillTask> skillTasks = new HashSet<SkillTask>(0);
	private Set<ProjektTask> projektTasks = new HashSet<ProjektTask>(0);
	private Set<MitarbeiterTask> mitarbeiterTasks = new HashSet<MitarbeiterTask>(
			0);

	public Task() {
	}

	public Task(String taskName, String taskBeschreibung) {
		this.taskName = taskName;
		this.taskBeschreibung = taskBeschreibung;
	}

	public Task(String taskName, String taskBeschreibung,
			Set<AbteilungTask> abteilungTasks, Set<SkillTask> skillTasks,
			Set<ProjektTask> projektTasks, Set<MitarbeiterTask> mitarbeiterTasks) {
		this.taskName = taskName;
		this.taskBeschreibung = taskBeschreibung;
		this.abteilungTasks = abteilungTasks;
		this.skillTasks = skillTasks;
		this.projektTasks = projektTasks;
		this.mitarbeiterTasks = mitarbeiterTasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TaskID", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "TaskName", nullable = false, length = 30)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "TaskBeschreibung", nullable = false, length = 500)
	public String getTaskBeschreibung() {
		return this.taskBeschreibung;
	}

	public void setTaskBeschreibung(String taskBeschreibung) {
		this.taskBeschreibung = taskBeschreibung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<AbteilungTask> getAbteilungTasks() {
		return this.abteilungTasks;
	}

	public void setAbteilungTasks(Set<AbteilungTask> abteilungTasks) {
		this.abteilungTasks = abteilungTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<SkillTask> getSkillTasks() {
		return this.skillTasks;
	}

	public void setSkillTasks(Set<SkillTask> skillTasks) {
		this.skillTasks = skillTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<ProjektTask> getProjektTasks() {
		return this.projektTasks;
	}

	public void setProjektTasks(Set<ProjektTask> projektTasks) {
		this.projektTasks = projektTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<MitarbeiterTask> getMitarbeiterTasks() {
		return this.mitarbeiterTasks;
	}

	public void setMitarbeiterTasks(Set<MitarbeiterTask> mitarbeiterTasks) {
		this.mitarbeiterTasks = mitarbeiterTasks;
	}

}
